# codecov.yml
# Codecov configuration for BMHQ monorepo
# Tracks coverage per workspace with separate thresholds

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error

      # Per-workspace targets
      bmhq-platform:
        target: 55%
        paths:
          - "projects/bmhq-platform/src/**"
        flags:
          - bmhq-platform

      mission-control:
        target: 55%
        paths:
          - "projects/mission-control/src/**"
        flags:
          - mission-control

      agent-os:
        target: 60%
        paths:
          - "projects/agent-os/src/**"
        flags:
          - agent-os

    patch:
      default:
        target: 70%
        threshold: 10%

# Flag definitions (match matrix.workspace in CI)
flags:
  bmhq-platform:
    paths:
      - projects/bmhq-platform/src/
    carryforward: true

  mission-control:
    paths:
      - projects/mission-control/src/
    carryforward: true

  agent-os:
    paths:
      - projects/agent-os/src/
    carryforward: true

  # Uncomment as modules are built:
  # business-os:
  #   paths:
  #     - projects/business-os/src/
  #   carryforward: true
  # marketing-os:
  #   paths:
  #     - projects/marketing-os/src/
  #   carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "**/*.d.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/coverage/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/node_modules/**"
