name: "new-day-learning"
description: "Mobile-first ERP system for DDD services — client management, billing, scheduling, and reporting"
stack: "orbit"
status: planning
created: "2024-03-20"
updated: "2025-01-01"
